### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by charissamartin** [MontgomeryLab/tinyRNA#331] opened 2024-03-14 19:53 UTC
I am having installation issues. I've tried the three varieties of install levels (standard install of stable release, development release, and tiny-count standalone installation) and all are ending in error. Both of the stable and developmental releases result in the same error while trying to run setup.sh within the conda environment.

I am working from a Linux64 server. Here are the commands I tried, referenced from the install instructions, and their corresponding errors:
```
[charissa@hydra tinyRNA-1.5.0]$ conda create --name tinyrna
[charissa@hydra tinyRNA-1.5.0]$ bash setup.sh
```

```
✓ Linux detected
✓ Conda is already installed for bash

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/charissa/anaconda3/lib/python3.7/site-packages/conda/cli/main                                               .py", line 98, in main
        return activator_main()
      File "/home/charissa/anaconda3/lib/python3.7/site-packages/conda/activate                                               .py", line 630, in main
        activator = Activator(shell, activator_args)
      File "/home/charissa/anaconda3/lib/python3.7/site-packages/conda/activate                                               .py", line 136, in __init__
        raise NotImplementedError()
    NotImplementedError

`$ /home/charissa/anaconda3/bin/conda shell.bash hook`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/charissa/anaconda3/bin/conda
             CONDA_PREFIX=/home/charissa/anaconda3
    CONDA_PROMPT_MODIFIER=
         CONDA_PYTHON_EXE=/home/charissa/anaconda3/bin/python
               CONDA_ROOT=/home/charissa/anaconda3
              CONDA_SHLVL=1
          LD_LIBRARY_PATH=/data/installed_programs/samtools_htslib/htslib:/usr/                                               local/genome/sail
                          fish/lib:/usr/local/genome/salmon/lib
                  MANPATH=/usr/share/man:
               MODULEPATH=/etc/scl/modulefiles:/usr/share/Modules/modulefiles:/                                               etc/modulefiles:/
                          usr/share/modulefiles
                     PATH=/home/charissa/anaconda3/bin:/home/charissa/.local/bi                                               n:/home/charissa/
                          bin:/usr/share/Modules/bin:/usr/local/genome/VICTOR:/                                               home/charissa/bin
                          :/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/u                                               sr/local/genome/b
                          in:/usr/share/perl5/htslib:/opt/julia-1.9.4/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
  __MODULES_SHARE_MANPATH=:1

     active environment : base
    active env location : /home/charissa/anaconda3
            shell level : 1
       user config file : /home/charissa/.condarc
 populated config files :
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : /home/charissa/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/charissa/anaconda3/pkgs
                          /home/charissa/.conda/pkgs
       envs directories : /home/charissa/anaconda3/envs
                          /home/charissa/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Linux/5.14                                               .0-305.el9.x86_64 centos/9 glibc/2.34
                UID:GID : 1174:1174
             netrc file : None
           offline mode : False
```

```
[charissa@hydra ~]$ # Clone the repository into a local directory
 git clone https://github.com/MontgomeryLab/tinyrna.git
 cd tinyrna

# Install the tinyrna environment and dependencies
 ./setup.sh
```

```
Cloning into 'tinyrna'...
remote: Enumerating objects: 9191, done.
remote: Counting objects: 100% (1208/1208), done.
remote: Compressing objects: 100% (380/380), done.
remote: Total 9191 (delta 847), reused 1164 (delta 825), pack-reused 7983
Receiving objects: 100% (9191/9191), 59.54 MiB | 29.38 MiB/s, done.
Resolving deltas: 100% (6640/6640), done.
Updating files: 100% (156/156), done.
✓ Linux detected
✓ Conda is already installed for bash

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/charissa/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 98, in main
        return activator_main()
      File "/home/charissa/anaconda3/lib/python3.7/site-packages/conda/activate.py", line 630, in main
        activator = Activator(shell, activator_args)
      File "/home/charissa/anaconda3/lib/python3.7/site-packages/conda/activate.py", line 136, in __init__
        raise NotImplementedError()
    NotImplementedError

`$ /home/charissa/anaconda3/bin/conda shell.bash hook`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/charissa/anaconda3/bin/conda
             CONDA_PREFIX=/home/charissa/anaconda3
    CONDA_PROMPT_MODIFIER=
         CONDA_PYTHON_EXE=/home/charissa/anaconda3/bin/python
               CONDA_ROOT=/home/charissa/anaconda3
              CONDA_SHLVL=1
          LD_LIBRARY_PATH=/data/installed_programs/samtools_htslib/htslib:/usr/local/genome/sail
                          fish/lib:/usr/local/genome/salmon/lib
                  MANPATH=/usr/share/man:
               MODULEPATH=/etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/
                          usr/share/modulefiles
                     PATH=/home/charissa/anaconda3/bin:/home/charissa/.local/bin:/home/charissa/
                          bin:/usr/share/Modules/bin:/usr/local/genome/VICTOR:/home/charissa/bin
                          :/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/genome/b
                          in:/usr/share/perl5/htslib:/opt/julia-1.9.4/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
  __MODULES_SHARE_MANPATH=:1

     active environment : base
    active env location : /home/charissa/anaconda3
            shell level : 1
       user config file : /home/charissa/.condarc
 populated config files :
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : /home/charissa/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/charissa/anaconda3/pkgs
                          /home/charissa/.conda/pkgs
       envs directories : /home/charissa/anaconda3/envs
                          /home/charissa/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Linux/5.14.0-305.el9.x86_64 centos/9 glibc/2.34
                UID:GID : 1174:1174
             netrc file : None
           offline mode : False
```

```
[charissa@hydra ~]$ conda install -c bioconda -c conda-forge tiny-count
```
```
Solving environment: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/bioconda/linux-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(MaxRetryError('HTTPSConnectionPool(host=\'conda.anaconda.org\', port=443): Max retries exceeded with url: /bioconda/linux-64/repodata.json (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'ssl3_get_server_certificate\', \'certificate verify failed\')])")))'))
```

**Comment by AlexTate** [comment] 2024-03-18 21:26
Hi @charissamartin, thank you for bringing this to our attention. The first two errors were produced because your system has an outdated version of Conda installed. Version 4.5.11 was released in 2018 and it isn't compatible with our installation script.  You can update Conda with the following command:

```
conda update -n base conda
```

The third error is, as it states, an intermittent issue. I've just confirmed that the URL is live and returns the expected data. Anaconda occasionally has downtime, and while I've never encountered this particular error myself, [a quick search through the Bioconda recipes repo](https://github.com/bioconda/bioconda-recipes/issues?q=is%3Aissue+HTTP+000+CONNECTION+FAILED) shows that it recently happened to another user. When you see it just wait a bit and try again. It shouldn't be something that you see often. If the issue persists then there might be a problem with your local network configuration.

**Comment by charissamartin** [comment] 2024-03-19 16:30
Thanks, @AlexTate! I was having issues even updating the conda I had locally on my server profile. Luckily, the server admin helped me out and got an updated version of conda available globally. I've got it working now. :)

**Closed** 2024-03-19 16:31 UTC
